# Site Settings

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed]

# feed settings
title:		     "{{ site.data.settings.title }} | {{ site.data.settings.tagline }}"
google_plus_username: AleksandarTodorovićr3bl
facebook_username:    aleksandar.todorovic.r3bl
# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#   path:	     rss-feed.xml

sass:
  sass_dir: assets/css
  style: :nested
