title:  "Millennial"
tagline: "a Jekyll theme"
description:
author:
  name: "Paul Le"
  twitter: paululele

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Interesting Facts', file: 'facts.html'}
- {name: 'Learning Resources', file: 'resources.html'}
- {name: 'Sample Posts', file: 'sample-posts.html'}
- {name: 'Documentation', file: 'documentation.html'}
- {name: 'About', file: 'about.html'}
- {name: 'Contact', file: 'contact.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/Yoni_Keren'}
- {icon: 'facebook', link: 'https://www.facebook.com/yoni.keren'}
- {icon: 'instagram', link: 'https://instagram.com/kerenyoni'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yoni-keren-361498143/'}
- {icon: 'envelope', link: 'mailto:yoni.keren@yahoo.ca'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
